from drasi_core import PyReactionWrapper

class PyLogReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def with_default_template(self, added: str | None = None, updated: str | None = None, deleted: str | None = None) -> None: ...
    def with_route(self, query_id: str, added: str | None = None, updated: str | None = None, deleted: str | None = None) -> None: ...
    def build(self) -> PyLogReaction: ...

class PyLogReaction:
    @staticmethod
    def builder(id: str) -> PyLogReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
