from drasi_core import PyBootstrapProviderWrapper

class PyPostgresBootstrapProviderBuilder:
    def __init__(self) -> None: ...
    def with_host(self, host: str) -> None: ...
    def with_port(self, port: int) -> None: ...
    def with_database(self, database: str) -> None: ...
    def with_user(self, user: str) -> None: ...
    def with_password(self, password: str) -> None: ...
    def with_tables(self, tables: list[str]) -> None: ...
    def with_table(self, table: str) -> None: ...
    def build(self) -> PyPostgresBootstrapProvider: ...

class PyPostgresBootstrapProvider:
    @staticmethod
    def builder() -> PyPostgresBootstrapProviderBuilder: ...
    def into_bootstrap_wrapper(self) -> PyBootstrapProviderWrapper: ...
