from drasi_core import PyBootstrapProviderWrapper

class PyScriptFileBootstrapProviderBuilder:
    def __init__(self) -> None: ...
    def with_file_paths(self, paths: list[str]) -> None: ...
    def with_file(self, path: str) -> None: ...
    def build(self) -> PyScriptFileBootstrapProvider: ...

class PyScriptFileBootstrapProvider:
    @staticmethod
    def builder() -> PyScriptFileBootstrapProviderBuilder: ...
    @staticmethod
    def with_paths(paths: list[str]) -> PyScriptFileBootstrapProvider: ...
    def into_bootstrap_wrapper(self) -> PyBootstrapProviderWrapper: ...
