from drasi_core import PySourceWrapper

class PyPostgresSourceBuilder:
    def __init__(self, id: str) -> None: ...
    def with_host(self, host: str) -> None: ...
    def with_port(self, port: int) -> None: ...
    def with_database(self, database: str) -> None: ...
    def with_user(self, user: str) -> None: ...
    def with_password(self, password: str) -> None: ...
    def with_tables(self, tables: list[str]) -> None: ...
    def add_table(self, table: str) -> None: ...
    def with_slot_name(self, slot_name: str) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyPostgresSource: ...

class PyPostgresSource:
    @staticmethod
    def builder(id: str) -> PyPostgresSourceBuilder: ...
    def into_source_wrapper(self) -> PySourceWrapper: ...
