from drasi_core import PyStateStoreProviderWrapper

class PyRedbStateStoreProvider:
    def __init__(self, path: str) -> None: ...
    def into_state_store_wrapper(self) -> PyStateStoreProviderWrapper: ...
