from drasi_core import PyReactionWrapper

class PyGrpcReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_endpoint(self, endpoint: str) -> None: ...
    def with_timeout_ms(self, timeout_ms: int) -> None: ...
    def with_max_retries(self, retries: int) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyGrpcReaction: ...

class PyGrpcReaction:
    @staticmethod
    def builder(id: str) -> PyGrpcReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
