from drasi_core import PyReactionWrapper

class PySseReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_host(self, host: str) -> None: ...
    def with_port(self, port: int) -> None: ...
    def with_sse_path(self, path: str) -> None: ...
    def with_heartbeat_interval_ms(self, interval_ms: int) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PySseReaction: ...

class PySseReaction:
    @staticmethod
    def builder(id: str) -> PySseReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
