from drasi_core import PyReactionWrapper

class PyPostgresStoredProcReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_hostname(self, hostname: str) -> None: ...
    def with_port(self, port: int) -> None: ...
    def with_database(self, database: str) -> None: ...
    def with_user(self, user: str) -> None: ...
    def with_password(self, password: str) -> None: ...
    def with_ssl(self, enable: bool) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_command_timeout_ms(self, timeout_ms: int) -> None: ...
    def with_retry_attempts(self, attempts: int) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    async def build(self) -> PyPostgresStoredProcReaction: ...

class PyPostgresStoredProcReaction:
    @staticmethod
    def builder(id: str) -> PyPostgresStoredProcReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
