from typing import Any

from drasi_core import DispatchMode, PyQueryConfig, PySourceWrapper, PyReactionWrapper, PyIndexBackendWrapper, PyStateStoreProviderWrapper

# Enums

class ComponentStatus:
    Starting: ComponentStatus
    Running: ComponentStatus
    Stopping: ComponentStatus
    Stopped: ComponentStatus
    Error: ComponentStatus

class ComponentType:
    Source: ComponentType
    Query: ComponentType
    Reaction: ComponentType

class LogLevel:
    Trace: LogLevel
    Debug: LogLevel
    Info: LogLevel
    Warn: LogLevel
    Error: LogLevel

# Data classes

class ComponentEvent:
    @property
    def component_id(self) -> str: ...
    @property
    def component_type(self) -> ComponentType: ...
    @property
    def status(self) -> ComponentStatus: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def message(self) -> str | None: ...

class LogMessage:
    @property
    def timestamp(self) -> str: ...
    @property
    def level(self) -> LogLevel: ...
    @property
    def message(self) -> str: ...
    @property
    def instance_id(self) -> str: ...
    @property
    def component_id(self) -> str: ...
    @property
    def component_type(self) -> ComponentType: ...

class QueryResult:
    @property
    def query_id(self) -> str: ...
    @property
    def timestamp(self) -> str: ...
    @property
    def results(self) -> Any: ...
    @property
    def metadata(self) -> Any: ...

# Streaming

class EventStream:
    def __aiter__(self) -> EventStream: ...
    async def __anext__(self) -> ComponentEvent: ...

class EventSubscription:
    @property
    def history(self) -> list[ComponentEvent]: ...
    def __aiter__(self) -> EventStream: ...

class LogStream:
    def __aiter__(self) -> LogStream: ...
    async def __anext__(self) -> LogMessage: ...

class LogSubscription:
    @property
    def history(self) -> list[LogMessage]: ...
    def __aiter__(self) -> LogStream: ...

# Query builder

class Query:
    @staticmethod
    def cypher(id: str) -> Query: ...
    @staticmethod
    def gql(id: str) -> Query: ...
    def query(self, query: str) -> None: ...
    def from_source(self, source_id: str) -> None: ...
    def auto_start(self, auto_start: bool) -> None: ...
    def enable_bootstrap(self, enable: bool) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_dispatch_buffer_capacity(self, capacity: int) -> None: ...
    def with_dispatch_mode(self, mode: DispatchMode) -> None: ...
    def build(self) -> PyQueryConfig: ...

# DrasiLib builder

class DrasiLibBuilder:
    def __init__(self) -> None: ...
    def with_id(self, id: str) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_dispatch_buffer_capacity(self, capacity: int) -> None: ...
    def with_source(self, source: PySourceWrapper) -> None: ...
    def with_query(self, query: PyQueryConfig) -> None: ...
    def with_reaction(self, reaction: PyReactionWrapper) -> None: ...
    def with_index_provider(self, provider: PyIndexBackendWrapper) -> None: ...
    def with_state_store_provider(self, provider: PyStateStoreProviderWrapper) -> None: ...
    async def build(self) -> PyDrasiLib: ...

# DrasiLib

class PyDrasiLib:
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def is_running(self) -> bool: ...
    async def add_source(self, source: PySourceWrapper) -> None: ...
    async def remove_source(self, id: str) -> None: ...
    async def start_source(self, id: str) -> None: ...
    async def stop_source(self, id: str) -> None: ...
    async def list_sources(self) -> list[tuple[str, ComponentStatus]]: ...
    async def get_source_status(self, id: str) -> ComponentStatus: ...
    async def add_query(self, query: PyQueryConfig) -> None: ...
    async def remove_query(self, id: str) -> None: ...
    async def start_query(self, id: str) -> None: ...
    async def stop_query(self, id: str) -> None: ...
    async def list_queries(self) -> list[tuple[str, ComponentStatus]]: ...
    async def get_query_status(self, id: str) -> ComponentStatus: ...
    async def add_reaction(self, reaction: PyReactionWrapper) -> None: ...
    async def remove_reaction(self, id: str) -> None: ...
    async def start_reaction(self, id: str) -> None: ...
    async def stop_reaction(self, id: str) -> None: ...
    async def list_reactions(self) -> list[tuple[str, ComponentStatus]]: ...
    async def get_reaction_status(self, id: str) -> ComponentStatus: ...
    async def subscribe_source_events(self, id: str) -> EventSubscription: ...
    async def subscribe_query_events(self, id: str) -> EventSubscription: ...
    async def subscribe_reaction_events(self, id: str) -> EventSubscription: ...
    async def subscribe_source_logs(self, id: str) -> LogSubscription: ...
    async def subscribe_query_logs(self, id: str) -> LogSubscription: ...
    async def subscribe_reaction_logs(self, id: str) -> LogSubscription: ...
