from typing import Any

from drasi_core import PySourceWrapper

class PyPropertyMap: ...

class PyPropertyMapBuilder:
    def __init__(self) -> None: ...
    def with_string(self, key: str, value: str) -> None: ...
    def with_integer(self, key: str, value: int) -> None: ...
    def with_float(self, key: str, value: float) -> None: ...
    def with_bool(self, key: str, value: bool) -> None: ...
    def with_null(self, key: str) -> None: ...
    def build(self) -> PyPropertyMap: ...

class PyApplicationSourceHandle:
    async def send_node_insert(self, id: str, labels: list[str], properties: PyPropertyMap) -> None: ...
    async def send_node_update(self, id: str, labels: list[str], properties: PyPropertyMap) -> None: ...
    async def send_delete(self, id: str, labels: list[str]) -> None: ...
    async def send_relation_insert(self, id: str, labels: list[str], properties: PyPropertyMap, start_node_id: str, end_node_id: str) -> None: ...
    def source_id(self) -> str: ...

class PyApplicationSource:
    def __init__(self, id: str, properties: dict[str, Any] | None = None) -> None: ...
    def get_handle(self) -> PyApplicationSourceHandle: ...
    def into_source_wrapper(self) -> PySourceWrapper: ...
