from drasi_core import PyBootstrapProviderWrapper

class PyApplicationBootstrapProviderBuilder:
    def __init__(self) -> None: ...
    def build(self) -> PyApplicationBootstrapProvider: ...

class PyApplicationBootstrapProvider:
    @staticmethod
    def builder() -> PyApplicationBootstrapProviderBuilder: ...
    def into_bootstrap_wrapper(self) -> PyBootstrapProviderWrapper: ...
