from drasi_core import PySourceWrapper

class PyHttpSourceBuilder:
    def __init__(self, id: str) -> None: ...
    def with_host(self, host: str) -> None: ...
    def with_port(self, port: int) -> None: ...
    def with_endpoint(self, endpoint: str) -> None: ...
    def with_timeout_ms(self, timeout_ms: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyHttpSource: ...

class PyHttpSource:
    @staticmethod
    def builder(id: str) -> PyHttpSourceBuilder: ...
    def into_source_wrapper(self) -> PySourceWrapper: ...
