from drasi_core import PySourceWrapper

class PyMockSourceBuilder:
    def __init__(self, id: str) -> None: ...
    def with_interval_ms(self, interval_ms: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyMockSource: ...

class PyMockSource:
    @staticmethod
    def builder(id: str) -> PyMockSourceBuilder: ...
    def into_source_wrapper(self) -> PySourceWrapper: ...
