from drasi_core import PyReactionWrapper

class PyProfilerReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_window_size(self, size: int) -> None: ...
    def with_report_interval_secs(self, secs: int) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyProfilerReaction: ...

class PyProfilerReaction:
    @staticmethod
    def builder(id: str) -> PyProfilerReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
