from drasi_core import PyIndexBackendWrapper

class PyRocksDbIndexProvider:
    def __init__(self, path: str, enable_archive: bool = False, direct_io: bool = False) -> None: ...
    def into_index_wrapper(self) -> PyIndexBackendWrapper: ...
