from drasi_core import PyReactionWrapper

class PyHttpReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_base_url(self, base_url: str) -> None: ...
    def with_token(self, token: str) -> None: ...
    def with_timeout_ms(self, timeout_ms: int) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> PyHttpReaction: ...

class PyHttpReaction:
    @staticmethod
    def builder(id: str) -> PyHttpReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...
