from typing import Any

from drasi_core import PyReactionWrapper

class PyApplicationReactionBuilder:
    def __init__(self, id: str) -> None: ...
    def with_query(self, query_id: str) -> None: ...
    def with_queries(self, queries: list[str]) -> None: ...
    def with_priority_queue_capacity(self, capacity: int) -> None: ...
    def with_auto_start(self, auto_start: bool) -> None: ...
    def build(self) -> tuple[PyApplicationReaction, PyApplicationReactionHandle]: ...

class PyApplicationReaction:
    @staticmethod
    def builder(id: str) -> PyApplicationReactionBuilder: ...
    def into_reaction_wrapper(self) -> PyReactionWrapper: ...

class PyApplicationReactionHandle:
    def reaction_id(self) -> str: ...
    async def as_stream(self) -> PyResultStream | None: ...

class PyResultStream:
    def __aiter__(self) -> PyResultStream: ...
    async def __anext__(self) -> Any: ...
